baseurl = ""
title = "Code, lol."
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
pygmentsCodeFences = true
pygmentsStyle = "colorful"

[Author]
  name = "Michael Poteat"
  bio = "Software engineer and researcher in SF. Interests in machine learning, programming, pure mathematics and many other topics."
  avatar = "img/avatar.png"

[Params]
  subtitle = "Mike's code blog. Come ye all and rejoice!" # Subtitle of your site
  description = "Mike's code blog about programming, math, and science." # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  postSections = ["post"]
  mathjax = true # Enable MathJax
  customCSS = ["css/custom.css"] # Include custom CSS files

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[markup.goldmark.renderer]
  unsafe= true
